package vu.lt.mybatis.model;

import java.util.List;

public class Model {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MODEL.ID
     *
     * @mbg.generated Mon Apr 26 23:26:16 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MODEL.MODEL
     *
     * @mbg.generated Mon Apr 26 23:26:16 EEST 2021
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MODEL.TYPE
     *
     * @mbg.generated Mon Apr 26 23:26:16 EEST 2021
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODEL.ID
     *
     * @return the value of PUBLIC.MODEL.ID
     *
     * @mbg.generated Mon Apr 26 23:26:16 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODEL.ID
     *
     * @param id the value for PUBLIC.MODEL.ID
     *
     * @mbg.generated Mon Apr 26 23:26:16 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODEL.MODEL
     *
     * @return the value of PUBLIC.MODEL.MODEL
     *
     * @mbg.generated Mon Apr 26 23:26:16 EEST 2021
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODEL.MODEL
     *
     * @param model the value for PUBLIC.MODEL.MODEL
     *
     * @mbg.generated Mon Apr 26 23:26:16 EEST 2021
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODEL.TYPE
     *
     * @return the value of PUBLIC.MODEL.TYPE
     *
     * @mbg.generated Mon Apr 26 23:26:16 EEST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODEL.TYPE
     *
     * @param type the value for PUBLIC.MODEL.TYPE
     *
     * @mbg.generated Mon Apr 26 23:26:16 EEST 2021
     */
    public void setType(String type) {
        this.type = type;
    }

    private List<Manufacturer> manufacturers;

    public List<Manufacturer> getManufacturers() {
        return manufacturers;
    }

    public void setManufacturers(List<Manufacturer> manufacturers) {
        this.manufacturers = manufacturers;
    }
}
