package vu.lt.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.Building;
@Mapper
public interface BuildingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BUILDING
     *
     * @mbg.generated Mon Apr 26 23:26:16 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BUILDING
     *
     * @mbg.generated Mon Apr 26 23:26:16 EEST 2021
     */
    int insert(Building record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BUILDING
     *
     * @mbg.generated Mon Apr 26 23:26:16 EEST 2021
     */
    Building selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BUILDING
     *
     * @mbg.generated Mon Apr 26 23:26:16 EEST 2021
     */
    List<Building> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BUILDING
     *
     * @mbg.generated Mon Apr 26 23:26:16 EEST 2021
     */
    int updateByPrimaryKey(Building record);

    List<Building> selectManufacturerBuildings(Integer manufacturerID);
}
